name: C Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    
    - name: Install Dependencies
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 3
        max_attempts: 3
        command: |
          sudo apt-get update
          sudo apt-get install -y gcc make
      
    - name: Install CS50 Library
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 3
        max_attempts: 3
        command: |
          git clone https://github.com/cs50/libcs50.git
          cd libcs50
          sudo make install
          cd ..

    - name: Build
      run: |
        for dir in week*/*/ ; do
          if [ -f "$dir"/*.c ]; then
            cd "$dir"
            gcc -o program *.c -lcs50 -lm || exit 1
            cd ../..
          fi
        done

    - name: Test
      if: success()
      run: |
        for dir in week*/*/ ; do
          if [ -f "$dir"/program ]; then
            cd "$dir"
            ./program || true
            cd ../..
          fi
        done